# Generated by Django 5.2.16 on 2026-07-10 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CinemaChain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "chain_name",
                    models.CharField(max_length=255, verbose_name="連鎖名稱"),
                ),
                (
                    "official_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="官方網站"
                    ),
                ),
                (
                    "crawl_url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="爬蟲來源網址",
                    ),
                ),
                (
                    "booking_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="訂票網址"
                    ),
                ),
                (
                    "all_locations_assumed_showing",
                    models.BooleanField(default=True, verbose_name="預設全影城上映"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                ("active", models.BooleanField(default=True, verbose_name="啟用")),
                (
                    "created_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "影城連鎖",
                "verbose_name_plural": "影城連鎖",
                "db_table": "cinema_chains",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CinemaLocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location_name",
                    models.CharField(max_length=255, verbose_name="據點名稱"),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="顯示名稱"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="地址"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="縣市"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="行政區"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="緯度"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="經度"),
                ),
                (
                    "source_location_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="來源據點代碼",
                    ),
                ),
                (
                    "location_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="據點網址"
                    ),
                ),
                (
                    "source_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="來源網址"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                ("active", models.BooleanField(default=True, verbose_name="啟用")),
                (
                    "created_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "影城據點",
                "verbose_name_plural": "影城據點",
                "db_table": "cinema_locations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CrawlRun",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("run_type", models.CharField(max_length=255, verbose_name="批次類型")),
                (
                    "source_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="來源名稱"
                    ),
                ),
                (
                    "source_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="來源網址"
                    ),
                ),
                (
                    "started_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "finished_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="結束時間"
                    ),
                ),
                ("status", models.CharField(max_length=255, verbose_name="狀態")),
                (
                    "rows_found",
                    models.IntegerField(blank=True, null=True, verbose_name="發現筆數"),
                ),
                (
                    "rows_saved",
                    models.IntegerField(blank=True, null=True, verbose_name="儲存筆數"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="錯誤訊息"),
                ),
            ],
            options={
                "verbose_name": "爬蟲批次",
                "verbose_name_plural": "爬蟲批次",
                "db_table": "crawl_runs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="KmlExport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "export_date",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="匯出日期"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=255, verbose_name="檔案路徑"),
                ),
                (
                    "placemark_count",
                    models.IntegerField(blank=True, null=True, verbose_name="地標數量"),
                ),
                (
                    "created_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="建立時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "KML 匯出",
                "verbose_name_plural": "KML 匯出",
                "db_table": "kml_exports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="片名")),
                (
                    "original_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="原文片名"
                    ),
                ),
                (
                    "release_date",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="上映日期"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                ("active", models.BooleanField(default=True, verbose_name="啟用")),
                (
                    "created_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "電影",
                "verbose_name_plural": "電影",
                "db_table": "movies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MovieTarget",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "target_scope",
                    models.CharField(max_length=255, verbose_name="追蹤範圍"),
                ),
                ("status", models.CharField(max_length=255, verbose_name="狀態")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "created_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "電影追蹤目標",
                "verbose_name_plural": "電影追蹤目標",
                "db_table": "movie_targets",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RawPage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source_url",
                    models.CharField(max_length=255, verbose_name="來源網址"),
                ),
                (
                    "local_path",
                    models.TextField(
                        blank=True, null=True, verbose_name="本機檔案路徑"
                    ),
                ),
                (
                    "content_sha256",
                    models.TextField(
                        blank=True, null=True, verbose_name="內容 SHA-256"
                    ),
                ),
                (
                    "http_status",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="HTTP 狀態碼"
                    ),
                ),
                (
                    "fetched_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="抓取時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "原始網頁",
                "verbose_name_plural": "原始網頁",
                "db_table": "raw_pages",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Showtime",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "show_date",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="放映日期"
                    ),
                ),
                (
                    "start_time",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "end_time",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="結束時間"
                    ),
                ),
                (
                    "auditorium",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="影廳"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="放映格式"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="語言"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="字幕"
                    ),
                ),
                (
                    "booking_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="訂票網址"
                    ),
                ),
                (
                    "source_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="來源網址"
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(blank=True, null=True, verbose_name="原始文字"),
                ),
                (
                    "created_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "場次",
                "verbose_name_plural": "場次",
                "db_table": "showtimes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="片名")),
                (
                    "aliases",
                    models.TextField(
                        blank=True, default="", verbose_name="別名（一行一個）"
                    ),
                ),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="追蹤日期"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="啟用追蹤"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="備註"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tracked_movies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_tracked_movies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最後修改者",
                    ),
                ),
            ],
            options={
                "verbose_name": "追蹤電影",
                "verbose_name_plural": "追蹤電影",
                "db_table": "tracked_movie",
                "ordering": ["sort_order", "title"],
            },
        ),
    ]
