# Generated by Django 5.2.16 on 2026-07-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="執行編號"
                    ),
                ),
                (
                    "worker_name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="執行機器"
                    ),
                ),
                (
                    "started_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "finished_at",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="結束時間"
                    ),
                ),
                (
                    "show_date",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="場次日期"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="unknown", max_length=32, verbose_name="整體狀態"
                    ),
                ),
                (
                    "movie_list_source",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="片單來源"
                    ),
                ),
                (
                    "movie_list_version",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="片單版本"
                    ),
                ),
                (
                    "movie_list_count",
                    models.IntegerField(blank=True, null=True, verbose_name="片單數量"),
                ),
                (
                    "cache_age_seconds",
                    models.IntegerField(blank=True, null=True, verbose_name="快取秒數"),
                ),
                (
                    "sources_total",
                    models.IntegerField(default=0, verbose_name="來源總數"),
                ),
                (
                    "sources_success",
                    models.IntegerField(default=0, verbose_name="成功來源"),
                ),
                (
                    "sources_failed",
                    models.IntegerField(default=0, verbose_name="失敗來源"),
                ),
                (
                    "showtimes_found",
                    models.IntegerField(default=0, verbose_name="解析場次"),
                ),
                (
                    "showtimes_saved",
                    models.IntegerField(default=0, verbose_name="寫入場次"),
                ),
                (
                    "git_push_status",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Git 推送"
                    ),
                ),
                (
                    "commit_sha",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Commit"
                    ),
                ),
                (
                    "payload",
                    models.TextField(
                        blank=True, null=True, verbose_name="原始報告 JSON"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收到時間"),
                ),
            ],
            options={
                "verbose_name": "執行報告",
                "verbose_name_plural": "執行報告",
                "db_table": "crawl_report",
                "ordering": ["-created_at"],
            },
        ),
    ]
