# Generated by Django 5.2.16 on 2026-07-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapdata", "0002_crawlreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedmovie",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="只有今天（台北時間）不早於此日期，才會被納入爬蟲收集；留空＝一律收集。",
                null=True,
                verbose_name="上映日期",
            ),
        ),
    ]
